<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZOdkAFx\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZOdkAFx/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZOdkAFx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZOdkAFx\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerZOdkAFx\srcApp_KernelProdContainer([
    'container.build_hash' => 'ZOdkAFx',
    'container.build_id' => '0f072602',
    'container.build_time' => 1565911095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZOdkAFx');
