<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'dashboard' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'crawl' => [[], ['_controller' => 'App\\Controller\\HomeController::crawlAction'], [], [['text', '/api/crawl']], [], []],
    'save' => [[], ['_controller' => 'App\\Controller\\HomeController::saveAction'], [], [['text', '/api/save']], [], []],
    'fetch' => [[], ['_controller' => 'App\\Controller\\HomeController::fetchData'], [], [['text', '/api/fetch']], [], []],
];
