<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.b82e9a70.js',
                '/build/0.60a0592e.js',
                '/build/app.5824c909.js',
            ],
        ],
        'css/app' => [
            'js' => [
                '/build/runtime.b82e9a70.js',
            ],
            'css' => [
                '/build/css/app.82c6ab28.css',
            ],
        ],
    ],
],

]];
