<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p2qNg9H' shared service.

return $this->privates['.service_locator.p2qNg9H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BaseController::setLoggerService' => ['privates', '.service_locator.ysi3U3A', 'get_ServiceLocator_Ysi3U3AService.php', true],
    'App\\Controller\\BaseController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\HomeController::setLoggerService' => ['privates', '.service_locator.ysi3U3A', 'get_ServiceLocator_Ysi3U3AService.php', true],
    'App\\Controller\\HomeController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\BaseController:setLoggerService' => ['privates', '.service_locator.ysi3U3A', 'get_ServiceLocator_Ysi3U3AService.php', true],
    'App\\Controller\\BaseController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\HomeController:setLoggerService' => ['privates', '.service_locator.ysi3U3A', 'get_ServiceLocator_Ysi3U3AService.php', true],
    'App\\Controller\\HomeController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\BaseController::setLoggerService' => '?',
    'App\\Controller\\BaseController::setViewHandler' => '?',
    'App\\Controller\\HomeController::setLoggerService' => '?',
    'App\\Controller\\HomeController::setViewHandler' => '?',
    'App\\Controller\\BaseController:setLoggerService' => '?',
    'App\\Controller\\BaseController:setViewHandler' => '?',
    'App\\Controller\\HomeController:setLoggerService' => '?',
    'App\\Controller\\HomeController:setViewHandler' => '?',
]);
