<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ysi3U3A' shared service.

return $this->privates['.service_locator.ysi3U3A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'loggerService' => ['privates', 'App\\Service\\LoggerService', 'getLoggerServiceService.php', true],
], [
    'loggerService' => 'App\\Service\\LoggerService',
]);
