<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8RGq07\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8RGq07/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS8RGq07.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS8RGq07\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerS8RGq07\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'S8RGq07',
    'container.build_id' => '1a78dda3',
    'container.build_time' => 1565905699,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS8RGq07');
